#!/usr/bin/env python3
"""
generate_metadata.py
Generate judul, deskripsi, dan tags YouTube yang unik setiap kali.
"""

import random
import time
import os
import sys

THEMES = [
    "night_cafe", "rainy_window", "cozy_bedroom",
    "forest_dawn", "city_rooftop", "library"
]

ADJECTIVES = [
    "Cozy", "Peaceful", "Dreamy", "Nostalgic", "Warm", "Soft", "Gentle",
    "Mellow", "Serene", "Tranquil", "Soothing", "Late Night", "Early Morning",
    "Rainy Day", "Autumn", "Winter", "Midnight", "Golden Hour", "Cloudy",
    "Misty", "Quiet", "Calm", "Relaxing", "Aesthetic"
]

NOUNS = [
    "Vibes", "Study Session", "Coffee Break", "Focus Mode", "Work Music",
    "Chill Beats", "Night Beats", "Rain Sounds", "Cafe Ambience",
    "Music to Study/Relax", "Beats to Chill", "Lo-fi Journey",
    "City Nights", "Bedroom Pop", "Piano Café"
]

HASHTAGS = [
    "#lofi", "#lofihiphop", "#studymusic", "#chillbeats", "#lofimusic",
    "#studywithme", "#focusmusic", "#relaxingmusic", "#lofichill",
    "#backgroundmusic", "#aestheticmusic", "#lofibeats", "#workmusic",
    "#coffeeshop", "#productivity", "#meditation", "#sleepmusic",
    "#pianomusic", "#jazzvibes", "#indiemusic"
]

DESCRIPTIONS = [
    "Enjoy {duration} hour of AI-generated lo-fi music to help you focus, study, or relax. Every track is uniquely generated by a machine learning model trained on thousands of songs.",
    "A {duration}-hour journey through AI-crafted lo-fi beats. Let the music carry you through your study session, work, or late-night relaxation.",
    "{duration} hour of procedurally generated lo-fi hip hop beats. Perfect for studying, working, or just unwinding after a long day.",
    "Lose yourself in {duration} hours of unique, AI-composed lo-fi music. No two sessions are ever the same.",
    "Your {duration}-hour companion for focus and creativity — AI-generated lo-fi beats that never repeat.",
]

YOUTUBE_TAGS = [
    "lofi", "lo-fi", "lofi hip hop", "study music", "chill beats",
    "lofi music", "study with me", "focus music", "relaxing music",
    "lofi chill", "background music", "aesthetic music", "lofi beats",
    "work music", "coffee shop music", "lo fi hip hop", "lofi radio",
    "beats to study to", "music to relax to", "1 hour lofi",
    "lofi playlist", "no copyright music", "royalty free music",
    "AI music", "generated music", "machine learning music",
    "piano lofi", "jazz lofi", "bedroom pop", "indie lofi"
]


def main():
    # Generate seed berdasarkan waktu untuk keunikan
    seed = int(time.time()) % 100000
    rng = random.Random(seed)

    theme = rng.choice(THEMES)
    adj = rng.choice(ADJECTIVES)
    noun = rng.choice(NOUNS)

    # Judul
    templates = [
        f"{adj} Lo-fi {noun} 🎵 [1 Hour]",
        f"1 Hour of {adj} Lo-fi {noun}",
        f"Lo-fi {noun} - {adj} Beats 🎧 1 Hour",
        f"{adj} {noun} | Lo-fi Hip Hop Mix | 1 Hour",
        f"🎵 {adj} Lo-fi Beats | {noun} | 1 Hour",
    ]
    title = rng.choice(templates)

    # Deskripsi
    desc_template = rng.choice(DESCRIPTIONS).format(duration="1")
    hashtags = rng.sample(HASHTAGS, 8)

    description = f"""{desc_template}

🎵 Powered by AI / Machine Learning
🎨 Visuals: Procedurally generated lo-fi animation
⏱️ Duration: 1 Hour

Perfect for:
✅ Studying & Focus
✅ Working from Home
✅ Reading & Relaxing
✅ Sleeping & Meditation

{chr(10).join(hashtags)}

---
This music is AI-generated using a Variational Autoencoder (VAE) model trained on lo-fi music patterns. Each track is unique and procedurally synthesized.
"""

    # Tags
    tags = rng.sample(YOUTUBE_TAGS, 20)
    tags_str = ",".join(tags)

    # Tulis ke file env untuk dibaca GitHub Actions
    with open("/tmp/lofi_metadata.env", "w") as f:
        # Escape untuk bash
        title_escaped = title.replace('"', '\\"').replace('$', '\\$').replace('`', '\\`')
        desc_escaped = description.replace('"', '\\"').replace('$', '\\$').replace('`', '\\`').replace('\n', '\\n')
        f.write(f'TITLE="{title_escaped}"\n')
        f.write(f'DESCRIPTION="{desc_escaped}"\n')
        f.write(f'TAGS="{tags_str}"\n')
        f.write(f'SEED={seed}\n')
        f.write(f'THEME={theme}\n')

    print(f"[metadata] Title: {title}")
    print(f"[metadata] Theme: {theme}")
    print(f"[metadata] Seed: {seed}")
    print(f"[metadata] Tags: {tags_str[:80]}...")


if __name__ == "__main__":
    main()
